#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "instructions.h"

#define memorySize 8192
#define memoryPartition 20
#define MAX_LINE_SIZE 80
#define MAX_SYMBOL_NAME_LENGTH 32
#define TRUE 1
#define FALSE 0
#define REGISTERS 16
#define INSTRUCTIONS_AMOUNT 16
#define IMMEDIATE_ADDRESING 0x01
#define DIRECT_ADDRESING 0x02
#define INDEX_ADDRESSING 0x04
#define REGISTER_DIRECT_ADDRESSING 0x08
#define ALL_ADDRESSING_METHODS IMMEDIATE_ADDRESING | DIRECT_ADDRESING | INDEX_ADDRESSING | REGISTER_DIRECT_ADDRESSING
#define DIRECT_INDEX_REGISTER_ADDRESSING DIRECT_ADDRESING | INDEX_ADDRESSING | REGISTER_DIRECT_ADDRESSING

#endif